# Generated by Django 5.2.11 on 2026-05-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='COO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='countries/')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_in_india',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('Course_title', models.CharField(max_length=100)),
                ('course1', models.CharField(blank=True, max_length=100, null=True)),
                ('course2', models.CharField(blank=True, max_length=100, null=True)),
                ('course3', models.CharField(blank=True, max_length=100, null=True)),
                ('course4', models.CharField(blank=True, max_length=100, null=True)),
                ('course5', models.CharField(blank=True, max_length=100, null=True)),
                ('course6', models.CharField(blank=True, max_length=100, null=True)),
                ('course7', models.CharField(blank=True, max_length=100, null=True)),
                ('course8', models.CharField(blank=True, max_length=100, null=True)),
                ('course9', models.CharField(blank=True, max_length=100, null=True)),
                ('course10', models.CharField(blank=True, max_length=100, null=True)),
                ('course11', models.CharField(blank=True, max_length=100, null=True)),
                ('course12', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('studied_at', models.CharField(choices=[('India', 'India'), ('Abroad', 'Abroad')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('studied_at', models.CharField(choices=[('India', 'India'), ('Abroad', 'Abroad')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('highlight1', models.CharField(blank=True, max_length=200, null=True)),
                ('highlight2', models.CharField(blank=True, max_length=200, null=True)),
                ('highlight3', models.CharField(blank=True, max_length=200, null=True)),
                ('highlight4', models.CharField(blank=True, max_length=200, null=True)),
                ('highlight5', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
