# Generated by Django 5.2.11 on 2026-05-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannervideo',
            options={'verbose_name': 'Banner Video', 'verbose_name_plural': 'Banner Videos'},
        ),
        migrations.AlterModelOptions(
            name='ceo',
            options={'verbose_name': 'CEO', 'verbose_name_plural': 'CEOs'},
        ),
        migrations.AlterModelOptions(
            name='coo',
            options={'verbose_name': 'COO', 'verbose_name_plural': 'COOs'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='courses_in_india',
            options={'verbose_name': 'Course in India', 'verbose_name_plural': 'Courses in India'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='graduate',
            options={'verbose_name': 'Graduate', 'verbose_name_plural': 'Graduates'},
        ),
        migrations.AlterModelOptions(
            name='language_courses',
            options={'verbose_name': 'Language Course', 'verbose_name_plural': 'Language Courses'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RenameField(
            model_name='graduate',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='graduate',
            old_name='University',
            new_name='university',
        ),
    ]
