# Generated by Django 5.2.11 on 2026-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bannervideo_options_alter_ceo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('country', models.CharField(choices=[('India', 'India'), ('Abroad', 'Abroad')], max_length=20)),
                ('Course_title', models.CharField(max_length=100)),
                ('course1', models.CharField(blank=True, max_length=100, null=True)),
                ('course2', models.CharField(blank=True, max_length=100, null=True)),
                ('course3', models.CharField(blank=True, max_length=100, null=True)),
                ('course4', models.CharField(blank=True, max_length=100, null=True)),
                ('course5', models.CharField(blank=True, max_length=100, null=True)),
                ('course6', models.CharField(blank=True, max_length=100, null=True)),
                ('course7', models.CharField(blank=True, max_length=100, null=True)),
                ('course8', models.CharField(blank=True, max_length=100, null=True)),
                ('course9', models.CharField(blank=True, max_length=100, null=True)),
                ('course10', models.CharField(blank=True, max_length=100, null=True)),
                ('course11', models.CharField(blank=True, max_length=100, null=True)),
                ('course12', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Course in India',
                'verbose_name_plural': 'Courses in India',
            },
        ),
        migrations.DeleteModel(
            name='Courses_in_india',
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Abroad', 'Abroad')], default='India', max_length=20),
            preserve_default=False,
        ),
    ]
