# Generated by Django 5.2.11 on 2026-05-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_courses_options_alter_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
