# Generated by Django 5.2.7 on 2026-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('Abroad', 'Abroad')], max_length=20, null=True)),
                ('image', models.ImageField(upload_to='universities/')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
